### ISSUE TITLE
Кусок хода противники практически полностью повторяте ход игрока, кажется можно это обобщить

### ISSUE THREAD

**Issue by ahvastunov-itmo** [vadimkor56/Sea_battle-game#5]
https://github.com/vadimkor56/Sea_battle-improved-version-/blob/0812cfcb501a1b7d2e0387586c1913e5f34a7038/main.c#L63

**Comment by vadimkor56** [comment]
Там на самом деле, если приглядется, видно что повторяются только одна, максимум две строчки. Мне кажется, не резонно для них делать отдельную функцию. Возможно я что-то не заметил, скажите, если это так.
