### ISSUE TITLE
неужели надо пробегать по всему полю что бы убить один корабль?

### ISSUE THREAD

**Issue by ahvastunov-itmo** [vadimkor56/Sea_battle-game#8]
https://github.com/vadimkor56/Sea_battle-improved-version-/blob/0812cfcb501a1b7d2e0387586c1913e5f34a7038/functions.c#L18

**Comment by vadimkor56** [comment]
Попытался сделать эффективнее, получилась огроменная нечитаемая функция. Мне кажется вариант с пробегом по полю лучше, она хотя бы маленькая и понятная. Вы как считаете??

**Comment by ahvastunov-itmo** [comment]
Нет, потому что это не эффективно и имеет квадратичнуую зависимость от размера поля

**Comment by vadimkor56** [comment]
Все исправил (см. функцию killed)
