### ISSUE TITLE
Выделите функцию которая вам возращает статут соседней клети и не придется везде пистьа кучу ifов

### ISSUE THREAD

**Issue by ahvastunov-itmo** [vadimkor56/Sea_battle-game#9]
https://github.com/vadimkor56/Sea_battle-improved-version-/blob/0812cfcb501a1b7d2e0387586c1913e5f34a7038/functions.c#L76

**Comment by vadimkor56** [comment]
Сделал функцию статуса клетки, применил ее вместо ifов
